branches:
  only:
    - master
    - /^greenkeeper/.*$/

cache:
  yarn: true
  directories:
    - node_modules

notifications:
  email: false

node_js:
  - node

script:
  - yarn test

after_script:
  - cat ./coverage/lcov.info | coveralls
  - yarn semantic-release
