branches:
  only:
    - master
    - /^greenkeeper/.*$/

cache:
  yarn: true
  directories:
    - node_modules

notifications:
  email: false

node_js:
  - node

before_script:
  - npm install

script:
  - npm run test

after_script:
  - cat ./coverage/lcov.info | coveralls
  - npm run semantic-release
